module.exports = {
  apps: [
    {
      name: 'maidbot',
      script: './index.js',
      cwd: '/home/ubuntu/maidbot',
      node_args: '--max-old-space-size=512',
      max_memory_restart: '480M',
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 20,
      min_uptime: '30s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      merge_logs: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'p3-vector',
      script: 'api_server.py',
      cwd: '/home/ubuntu/qdrant',
      interpreter: '/home/ubuntu/qdrant/venv/bin/python',
      max_memory_restart: '2G',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '30s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      error_file: '/home/ubuntu/maidbot/logs/p3-err.log',
      out_file: '/home/ubuntu/maidbot/logs/p3-out.log',
      env: { PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'watchdog',
      script: './watchdog.js',
      cwd: '/home/ubuntu/maidbot',
      max_memory_restart: '100M',
      restart_delay: 5000,
      max_restarts: 50,
      min_uptime: '10s',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      error_file: './logs/watchdog-err.log',
      out_file: './logs/watchdog-out.log',
      env: { NODE_ENV: 'production' },
    },
  ],
};
